services:
  kafka-standalone:
    image: 'apache/kafka:3.7.0'
    hostname: kafka-standalone
    container_name: kafka-standalone
    ports:
      - '8083:8083'
      - '9092:9092'
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT_HOST://localhost:9092,PLAINTEXT://kafka-standalone:19092
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-standalone:29093
      - KAFKA_LISTENERS=CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_LOG_DIRS=/tmp/kraft-combined-logs
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
    user: root
    volumes:
      - "$PWD/kafka/config:/opt/kafka/config-cdc"
      - "$PWD/kafka/plugins:/opt/kafka/plugins"
      - "$PWD/data/kafka/tmp:/tmp"
      - "$PWD/data/kafka/out:/out-kafka"
    env_file:
      - .env
    deploy:
      replicas: 1

  kafka-sqlserver:
    hostname: kafka-sqlserver
    container_name: kafka-sqlserver
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword123!
      - MSSQL_PID=Developer
      - MSSQL_AGENT_ENABLED=True
    command: ["/bin/bash", "-c", "/opt/mssql/bin/sqlservr & until /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P $$SA_PASSWORD -Q 'SELECT 1' &> /dev/null; do sleep 1; done; /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P $$SA_PASSWORD -i /init.sql"]
    volumes:
      - "$PWD/sqlserver/init.sql:/init.sql"
    env_file:
      - .env
    deploy:
      replicas: 1
